### ISSUE TITLE
As a player, I want the game to keep track of various statistics (e.g., number of games played, win/loss ratio, total number of friends, number of achievements unlocked) so I can monitor my progress and compare my performance with that of other players.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#10]
* The game tracks and displays the following statistics for each user: number of games played, win/loss ratio, total number of friends, and number of achievements unlocked.
* The statistics are accessible and viewable in the user's profile page.
* The statistics are updated in real-time, immediately reflecting any changes resulting from game outcomes or social interactions.
* A user shall not be able to reset or alter his performance metrics.
* Users can compare their statistics with those of other players by viewing their profiles.

**Comment by random9nessss** [comment]
has been addressed under issue 331 in the following commit: 
[fa45902](https://github.com/sopra-fs24-group-17/server/pull/336/commits/fa45902f368bf112c2eed066a6f4684052eec18e)
