### ISSUE TITLE
As a player, I want to earn achievements for various in-game accomplishments (e.g., winning a certain number of games, playing a specific number of cards), so I can have goals to strive for and showcase my expertise.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#13]
* Players can view their achievements on their profile page as an extension of the automatically rendered game stats.
* Each achievement has a unique icon and description that reflects the accomplishment.
* Notifications are sent to players when they unlock a new achievement.

**Comment by random9nessss** [comment]
We left the user statistics at the win-loss ratio eventually.
