### ISSUE TITLE
As a competitive player of Exploding Kittens, I want to see my ranking among all players based on my win/loss ratio, so I can measure my skills against the broader community and strive for improvement.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#14]
* A ranking system is implemented that calculates each player's rank based on their win/loss ratio and the number of games played.
* Players can access a leaderboard from the dashboard that displays the top players and their rankings.
* The ranking updates in real-time as games conclude and results are processed.

**Comment by random9nessss** [comment]
This has been addressed in issue 292 and the following commit:
[fa45902](https://github.com/sopra-fs24-group-17/server/pull/336/commits/fa45902f368bf112c2eed066a6f4684052eec18e)
