### ISSUE TITLE
As a player in a game of Exploding Kittens, I want to engage in real-time chat with other players during the game, so we can discuss strategies, taunt each other, and enhance the social aspect of the game.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#15]
* The game interface includes a chatbox that displays messages from all players in real-time.
* Users can send text messages to the chatbox during their turns.
* The chat supports basic formatting (e.g., bold, italics) for expressive communication.
* There is an option to mute the chat.

**Comment by random9nessss** [comment]
Addressed in the following commits:
39c82c1
16693d3
c60a2cf
7591e1e
