### ISSUE TITLE
As a player, I want immersive and engaging sound effects that not only to enhance the fun but also serve as auditory feedback for certain gameplay actions.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#16]
* Key gameplay actions, such as shuffling or drawing cards, or explosions, shall trigger fitting sound effects.
* The sound effects shall be synchronised with the gameplay actions, making sure that auditory and visual feedback occurs in harmony.

**Comment by random9nessss** [comment]
Addressed in client issues #174 and #163
