### ISSUE TITLE
As a global user, I want the option of the game interface and tutorials to be available in a language of my choosing, in order to enhance my understanding of the rules and improve my gameplay experience.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#17]
* A language selection menu is offered in the dashboard, where registered users can select their language of choice out of a list.
* The languages available shall include at least English and German.
* The default language shall be English.
* Language preferences are saved to user's profile and applied across devices until changed.

**Comment by random9nessss** [comment]
We eventually left the language at english only.
