### ISSUE TITLE
As a registerd player, I want the game to automatically save progress to avoid losing my achievements and game status during unexpected disruptions.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#7]
* Game progress, including current game state and player achievements, is automatically saved at regular intervals and upon specific events (e.g., game completion).
* In the event of a disconnection or crash, players can resume their game from the last saved state.
* After disconnection, the first user to re-establish the game shall initiate a timer of 5 minutes during which all users that could not re-enter the session will automatically loose the game and be excluded for the continuation of the recent game session.
* Upon re-establishment of connection, an email is sent to all previously participating users, indicating that the timer began and providing a link to re-enter the session upon login.
* If no user can re-establish connection within a reasonable time-limit, the session shall be considered a win for every user.
* Players are notified about the autosave feature upon their first login.

**Comment by random9nessss** [comment]
Implemented by means of real-time game updates and websocket configuration with constant heartbeat.
